server:
  port: 8080
spring:
  application:
    name: "poc-rabbitmq"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbit:
  exchange: orders.exchange
  queue: orders.queue
  routing-key: order.created
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
