server:
  port: 8080
spring:
  application:
    name: "poc-rabbitmq"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest
rabbit:
  exchange: orders.exchange
  queue: orders.queue
  routing-key: order.created
  dlq:
    exchange: orders.dlx
    queue: orders.dlq
    routing-key: order.failed
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: poc-rabbitmq
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
